# Generated by Django 5.2 on 2025-04-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_owner_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='age',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='age',
        ),
    ]
