# Generated by Django 5.2 on 2025-04-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_owner_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='age',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
    ]
