# Generated by Django 5.2 on 2025-04-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_owner_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
