# Generated by Django 5.2 on 2025-04-05 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_animal_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='animals.animal'),
        ),
    ]
