# Generated by Django 5.2 on 2025-04-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_alter_animal_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
